ServiceName: "Tenders"

Server:
  host: "localhost"
  port: "8080"

Postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "963852741"
  DBName: "tenders"
  sslMode: "disable"
  pgDriver: "pgx"
