// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	"github.com/gofiber/fiber/v3"
)

// Controller describes methods, implemented by the http package.
type Handler interface {
	Ping() fiber.Handler
	CreateEmployee() fiber.Handler
	CreateOrganization() fiber.Handler
	AssignEmployeeToOrganization() fiber.Handler
	GetTenders() fiber.Handler
	GetUserTenders() fiber.Handler
	GetTenderStatus() fiber.Handler
	CreateTender() fiber.Handler
	EditTender() fiber.Handler
	UpdateTenderStatus() fiber.Handler
	RollbackTender() fiber.Handler
}
