// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	"zadanie-6105/backend/internal/domain"

	openapi "github.com/Lineblaze/avito_gen"
)

// Controller describes methods, implemented by the repository package.
type Repository interface {
	GetEmployeeByID(id int64) (*domain.Employee, error)
	GetEmployeeByUsername(username string) (*domain.Employee, error)
	CreateEmployee(employee *domain.Employee) (*domain.Employee, error)
	GetOrganizationByID(id int64) (*domain.Organization, error)
	CreateOrganization(organization *domain.Organization) (*domain.Organization, error)
	AssignEmployeeToOrganization(orgResp *domain.OrganizationResponsible) (*domain.OrganizationResponsible, error)
	IsUserResponsibleForOrganization(organizationId string) (bool, error)
	GetTenderByID(tenderId string) (*openapi.Tender, error)
	GetTenders() ([]openapi.Tender, error)
	GetUserTenders(userName string) ([]*openapi.Tender, error)
	GetTenderByVersion(tenderID string, version string) (*openapi.Tender, error)
	GetTenderStatus(tenderID string) (string, error)
	CreateTender(tender *openapi.Tender) (*openapi.Tender, error)
	EditTender(tender *openapi.Tender) (*openapi.Tender, error)
	UpdateTenderStatus(tenderID string, status string) error
}
