// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	openapi "github.com/Lineblaze/avito_gen"
)

// Controller describes methods, implemented by the repository package.
type Repository interface {
	GetEmployeeByID(id int64) (*openapi.Employee, error)
	GetEmployeeByUsername(username string) (*openapi.Employee, error)
	CreateEmployee(employee *openapi.Employee) (*openapi.Employee, error)
	GetOrganizationByID(id int64) (*openapi.Organization, error)
	CreateOrganization(organization *openapi.Organization) (*openapi.Organization, error)
	AssignEmployeeToOrganization(orgResp *openapi.OrganizationResponsible) (*openapi.OrganizationResponsible, error)
	IsUserResponsibleForOrganization(organizationId string) (bool, error)
	IsUserResponsibleForOrganizationByUsername(username string) (bool, error)
	GetResponsibleUsersForOrganization() ([]string, error)
	GetTenderByID(tenderId string) (*openapi.Tender, error)
	GetTenders() ([]openapi.Tender, error)
	GetUserTenders(userName string) ([]*openapi.Tender, error)
	GetTenderByVersion(tenderID string, version string) (*openapi.Tender, error)
	GetTenderStatus(tenderID string) (string, error)
	CreateTender(tender *openapi.Tender) (*openapi.Tender, error)
	EditTender(tender *openapi.Tender) (*openapi.Tender, error)
	UpdateTenderStatus(tenderID string, status string) error
	GetBidByID(bidId string) (*openapi.Bid, error)
	BidExistsByTenderID(tenderId string) (bool, error)
	GetBidsByTenderID(tenderId string) ([]*openapi.Bid, error)
	GetUserBids(userName string) ([]*openapi.Bid, error)
	GetBidByVersion(bidID string, version string) (*openapi.Bid, error)
	GetBidStatus(bidID string) (string, error)
	CreateBid(bid *openapi.Bid) (*openapi.Bid, error)
	EditBid(bid *openapi.Bid) (*openapi.Bid, error)
	UpdateBidStatus(bidID string, status string) error
	GetBidDecisions(bidId string) ([]openapi.BidDecision, error)
	RejectBid(bidId string) error
	UpdateBidDecision(bidId string, decision string, username string) error
	GetTenderStatusByBid(bidId string) (string, error)
	CloseTenderByBid(bidId string) error
	UpdateBidFeedback(bidId string, feedback string, username string) error
	GetBidReviewsByTenderId(tenderId string) ([]openapi.BidReview, error)
}
