// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	"zadanie-6105/backend/internal/domain"

	openapi "github.com/Lineblaze/avito_gen"
)

// Controller describes methods, implemented by the usecase package.
type UseCase interface {
	GetEmployeeByID(employeeID int64) (*domain.Employee, error)
	GetEmployeeByUserName(username string) (*domain.Employee, error)
	CreateEmployee(req *domain.CreateEmployeeRequest) (*domain.Employee, error)
	GetOrganizationByID(organizationID int64) (*domain.Organization, error)
	CreateOrganization(req *domain.CreateOrganizationRequest) (*domain.Organization, error)
	AssignEmployeeToOrganization(req *domain.AssignEmployeeToOrganizationRequest) (*domain.OrganizationResponsible, error)
	CheckUserOrganizationResponsibility(organizationId string) (bool, error)
	GetTenders() ([]openapi.Tender, error)
	GetUserTenders(userName string) ([]*openapi.Tender, error)
	GetTenderStatus(tenderID string) (string, error)
	CreateTender(req *openapi.CreateTenderRequest) (*openapi.Tender, error)
	EditTender(tenderID string, req *openapi.EditTenderRequest) (*openapi.Tender, error)
	UpdateTenderStatus(tenderID string, status string) error
	RollbackTender(tenderID string, version string) (*openapi.Tender, error)
}
